# Auto-Generated by cargo-bitbake 0.3.15
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get testing-again could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/testing-again/0.1.0"
SRC_URI += "git://github.com/GaetanMichel/testing-again;protocol=https;nobranch=1;branch=main"
SRCREV = "dc66ffe1244c700640e4e13584769ba2132e0406"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV_append = ".AUTOINC+dc66ffe124"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=2feaca6d57f0549b85acd8f8a4cce33a \
"

SUMMARY = "Tuto for including rust app in Petalinux build"
HOMEPAGE = "https://github.com/GaetanMichel/testing_again.git"
LICENSE = "MIT"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include testing-again-${PV}.inc
include testing-again.inc
